PRESETS = {
    "natural": {
        "pace": "moderate speed",
        "pitch": "moderate pitch",
        "monotony": "expressive and animated",
        "emotion": "neutral",
        "tone": "casual",
        "noise": "very clear",
        "reverberation": "very close-sounding",
    },
    "dramatic": {
        "pace": "slightly slowly",
        "pitch": "slightly low-pitch",
        "monotony": "very expressive and animated",
        "emotion": "excited",
        "tone": "dramatic",
        "noise": "very clear",
        "reverberation": "slightly close-sounding",
    },
    "professional": {
        "pace": "moderate speed",
        "pitch": "slightly low-pitch",
        "monotony": "slightly expressive and animated",
        "emotion": "neutral",
        "tone": "professional",
        "noise": "very clear",
        "reverberation": "very close-sounding",
    },
    "casual": {
        "pace": "slightly fast",
        "pitch": "moderate pitch",
        "monotony": "expressive and animated",
        "emotion": "happy",
        "tone": "casual",
        "noise": "very clear",
        "reverberation": "very close-sounding",
    },
    "narration": {
        "pace": "slightly slowly",
        "pitch": "moderate pitch",
        "monotony": "expressive and animated",
        "emotion": "neutral",
        "tone": "storytelling",
        "noise": "almost no noise",
        "reverberation": "slightly close-sounding",
    },
    "news_anchor": {
        "pace": "moderate speed",
        "pitch": "slightly low-pitch",
        "monotony": "slightly expressive and animated",
        "emotion": "neutral",
        "tone": "professional",
        "noise": "very clear",
        "reverberation": "very close-sounding",
    },
    "podcast": {
        "pace": "moderate speed",
        "pitch": "moderate pitch",
        "monotony": "expressive and animated",
        "emotion": "casual",
        "tone": "casual",
        "noise": "very clear",
        "reverberation": "slightly close-sounding",
    },
}

